<?php


/**
 * Implements hook_civicrm_buildForm()
 */
function civicrm_mailcheck_civicrm_buildForm($form_name, &$form) {
  $email_keys = array();
  if (!is_array($form->_rules)) { 
    return;
  }
  foreach ($form->_rules as $key => $rules) {
    if (!is_array($rules)) {
      continue;
    }
    foreach ($rules as $i => $rule) {
      if (is_array($rule) && $rule['type'] === 'email') {
        $email_keys[$key] = $key;
      }
    }
  }
  if (empty ($email_keys)) {
    return;
  }
  @$js_settings['email_fields'] = $email_keys;
  drupal_add_js(array('civicrm_mailcheck' => $js_settings), 'setting');
  drupal_add_js(drupal_get_path('module', 'civicrm_mailcheck') . '/js/jquery.mailcheck.js');
  drupal_add_js(drupal_get_path('module', 'civicrm_mailcheck') . '/js/civicrm_mailcheck.js');
}

/**
* Implements hook_help().
*/
function civicrm_mailcheck_help($path, $arg) {
  switch ($path) {
    case 'admin/help#civicrm_mailcheck':
      // Return a line-break version of the module README.txt
      return filter_filter('process', 1, NULL, file_get_contents( dirname(__FILE__) . "/README.txt") );
  }
}
